### ISSUE TITLE
Package "MangaDexPy" isn't detected

### ISSUE THREAD

**Issue by ctuluxfr** [Boubou0909/Mangas-dl#1]
Hello!

Congratulations for your wonderful Python project, this is exactly what I searched for. However, I can't make it work :(

Here's the full "log" of the errors I encountered :

`C:\Windows\system32>mangas-dl
Traceback (most recent call last):
  File "c:\users\jeremyd\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jeremyd\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jeremyd\AppData\Local\Programs\Python\Python39\Scripts\mangas-dl.exe\__main__.py", line 4, in <module>
  File "c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages\mangas_dl\__main__.py", line 5, in <module>
    from .mangas_dl_class import Mangas_dl
  File "c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages\mangas_dl\mangas_dl_class.py", line 4, in <module>
    from .pre_download_functions import *
  File "c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages\mangas_dl\pre_download_functions.py", line 4, in <module>
    import MangaDexPy
ModuleNotFoundError: No module named 'MangaDexPy'`

And when I try to install "MangaDexPy" :

`C:\Windows\system32>py -m pip install MangaDexPy
Requirement already satisfied: MangaDexPy in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (0.3.2)
Requirement already satisfied: aiohttp in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (from MangaDexPy) (3.7.4.post0)
Requirement already satisfied: requests==2.21.0 in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (from MangaDexPy) (2.21.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (from requests==2.21.0->MangaDexPy) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (from requests==2.21.0->MangaDexPy) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (from requests==2.21.0->MangaDexPy) (2021.5.30)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (from requests==2.21.0->MangaDexPy) (1.24.3)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (from aiohttp->MangaDexPy) (3.0.1)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (from aiohttp->MangaDexPy) (1.6.3)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (from aiohttp->MangaDexPy) (5.1.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (from aiohttp->MangaDexPy) (21.2.0)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\jeremyd\appdata\local\programs\python\python39\lib\site-packages (from aiohttp->MangaDexPy) (3.10.0.0)`

What can I do to solve this issue ?

Respectfully,
Ctulux

**Comment by Boubou0909** [comment]
Hello !
Thanks for your reply, I am currently working on it so I'm glad people find it useful !
However, I'm not a professional developper, I'm just a math and CS student trying to make a reliable project. That's why there are currently a lot of bugs (and I'm aware of that), but I'll do my best to fix them all. I don't know the source of this issue, but thanks for reporting it : I'll try to find a way to solve it.

I'll let this issue opened until your bug is fixed.

**Comment by ctuluxfr** [comment]
I understand. And this is a incredible project for a student.

Thank you so much for your answer :)

**Comment by Boubou0909** [comment]
To find an answer to your issue, I would need :
- the command you tried to launch
- if there are multiple versions of Python running on your computer
- if Python is in your PATH

**Comment by Boubou0909** [comment]
Ok I found the source of the issue : several packages on PyPI have quite the same name, so I made a wrong requirement in the setup.py file. The good package is not mangadexpy but MangaDex.py. I correct this immediatly, so try to reinstall mangas-dl !

**Comment by ctuluxfr** [comment]
I get this error after removing and reinstalling Mangas-dl. I searched for where the .json files would be stocked and I tried to add them manually using the .zip code package automatically generated by GitHub.

![Error](https://user-images.githubusercontent.com/78078206/125113743-8f7fb080-e0d8-11eb-8986-994611f441c7.PNG)

**Comment by ctuluxfr** [comment]
After this message, I set the path to mangas-dl manually. In my opinion, Python would have searched for the files in System32 and I get a new error when retrying.

![Error2](https://user-images.githubusercontent.com/78078206/125114242-3cf2c400-e0d9-11eb-807c-248e530ed9e9.PNG)

**Comment by ctuluxfr** [comment]
I'm sorry to spam you with all my messages/edits but I think that I found the solution.

![Solution_1](https://user-images.githubusercontent.com/78078206/125116626-8690de00-e0dc-11eb-9263-77cbd90bfef3.PNG)

I tried to install Pillow from PyPI and it seems to work correctly.
I let the script downloading the manga and I'll share you the results :D

**Comment by Boubou0909** [comment]
Good ! I'm glad you find a way to make it work !
I'm fixing this bug, and all shall be good.
Thanks for your help !

**Comment by ctuluxfr** [comment]
The download finished successfully !
You're welcome :D I'm glad I could help you.
